using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Taskalu
{
    /// <summary>
    /// AutoGenerateDetailsWindow.xaml の相互作用ロジック
    /// </summary>
    public partial class AutoGenerateDetailsWindow : Window
    {
        public ListAutoGenerate theAutoGenerate = new ListAutoGenerate();

        public AutoGenerateDetailsWindow()
        {
            InitializeComponent();
        }

        private void AutoGenerateLoaded(object sender, RoutedEventArgs e)
        {
            AutoGenerateTypeBox.SelectedIndex = (int)theAutoGenerate.Type;
            switch (theAutoGenerate.Type)
            {
                case (long)ListAutoGenerate.TypeName.A_Day_Of_Every_Month:
                    AutoGenerateType1Panel.Visibility = Visibility.Collapsed;
                    AutoGenerateType0Panel.Visibility = Visibility.Visible;
                    dayBox.SelectedIndex = (int)theAutoGenerate.Number0 - 1;
                    break;
                case (long)ListAutoGenerate.TypeName.A_Weekday_In_Every_Week:
                    AutoGenerateType0Panel.Visibility = Visibility.Collapsed;
                    AutoGenerateType1Panel.Visibility = Visibility.Visible;
                    weekdayBox.SelectedIndex = (int)theAutoGenerate.Number1;
                    break;
            }
            AutoGenerateName.Text = theAutoGenerate.Name;
            hourBox.SelectedIndex = (int)theAutoGenerate.Due_hour;
            minuteBox.SelectedIndex = (int)theAutoGenerate.Due_minute / 5;

            int priorityLen = theAutoGenerate.Priority.Length;
            if (priorityLen > 5) priorityLen = 5;
            priorityBox.SelectedIndex = 5 - priorityLen;

            // add combobox tempplate item
            templateBox.DataContext = TemplateListViewModel.tlv;
            TemplateListViewModel.tlv.Entries.Clear();
            var noneTemplate = new ListTemplate();
            noneTemplate.Id = 0;
            noneTemplate.Name = Properties.Resources.NW_None;
            noneTemplate.Order = -1;
            noneTemplate.Template = "";
            TemplateListViewModel.tlv.Entries.Add(noneTemplate);

            SQLiteClass.ExecuteSelectTableTemplate(SQLiteClass.dbpath, TemplateListViewModel.tlv);                                   

            // reflect the ID of template
            templateBox.SelectedIndex = 
                (int)SQLiteClass.ExecuteSelectTemplateOrderFromID(
                    SQLiteClass.dbpath, theAutoGenerate.Template) + 1;
        }

        private void AutoGenerateTypeBoxSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            switch (AutoGenerateTypeBox.SelectedIndex)
            {
                case (int)ListAutoGenerate.TypeName.A_Day_Of_Every_Month:
                    if ((AutoGenerateType0Panel != null) && (AutoGenerateType1Panel != null))
                    {
                        AutoGenerateType1Panel.Visibility = Visibility.Collapsed;
                        AutoGenerateType0Panel.Visibility = Visibility.Visible;
                        dayBox.SelectedIndex = (int)theAutoGenerate.Number0 - 1;
                    }
                    break;
                case (int)ListAutoGenerate.TypeName.A_Weekday_In_Every_Week:
                    if ((AutoGenerateType0Panel != null) && (AutoGenerateType1Panel != null))
                    {
                        AutoGenerateType0Panel.Visibility = Visibility.Collapsed;
                        AutoGenerateType1Panel.Visibility = Visibility.Visible;
                        weekdayBox.SelectedIndex = (int)theAutoGenerate.Number1;
                    }
                    break;
            }
        }

        private void dayBoxSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            theAutoGenerate.Number0 = dayBox.SelectedIndex + 1;
        }

        private void weekdayBoxSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            theAutoGenerate.Number1 = weekdayBox.SelectedIndex;
        }

        private void AutoGenerateDetailsOk_Click(object sender, RoutedEventArgs e)
        {
            theAutoGenerate.Type = AutoGenerateTypeBox.SelectedIndex;
            theAutoGenerate.Name = AutoGenerateName.Text;
            theAutoGenerate.Priority = String.Concat(Enumerable.Repeat("\u272e", 5 - priorityBox.SelectedIndex));

            var selectedTemplate = (ListTemplate)templateBox.SelectedItem;
            theAutoGenerate.Template = selectedTemplate.Id;

            theAutoGenerate.Number0 = dayBox.SelectedIndex + 1;
            theAutoGenerate.Number1 = weekdayBox.SelectedIndex;

            theAutoGenerate.Due_hour = hourBox.SelectedIndex;
            theAutoGenerate.Due_minute = minuteBox.SelectedIndex * 5;

            this.DialogResult = true;
        }
    }
}
