using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Taskalu
{
    /// <summary>
    /// AutoGenerateDetailsWindow.xaml の相互作用ロジック
    /// </summary>
    public partial class AutoGenerateDetailsWindow : Window
    {
        public ListAutoGenerate theAutoGenerate = new ListAutoGenerate();

        public AutoGenerateDetailsWindow()
        {
            InitializeComponent();


            // add combobox tempplate item
            templateBox.DataContext = TemplateListViewModel.tlv;
            TemplateListViewModel.tlv.Entries.Clear();
            var noneTemplate = new ListTemplate();
            noneTemplate.Id = 0;
            noneTemplate.Name = Properties.Resources.NW_None;
            noneTemplate.Order = -1;
            noneTemplate.Template = "";
            TemplateListViewModel.tlv.Entries.Add(noneTemplate);

            SQLiteClass.ExecuteSelectTableTemplate(SQLiteClass.dbpath, TemplateListViewModel.tlv);
        }

        private void AutoGenerateLoaded(object sender, RoutedEventArgs e)
        {

        }

        private void AutoGenerateDetailsOk_Click(object sender, RoutedEventArgs e)
        {

        }
    }
}
