//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskalu.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Taskalu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Copy {
            get {
                return ResourceManager.GetString("ContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date _Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_DateDetails {
            get {
                return ResourceManager.GetString("ContextMenu_DateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date _Summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_DateSummary {
            get {
                return ResourceManager.GetString("ContextMenu_DateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E_xit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_Exit {
            get {
                return ResourceManager.GetString("ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _New Task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContextMenu_NewTask {
            get {
                return ResourceManager.GetString("ContextMenu_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DD_Date {
            get {
                return ResourceManager.GetString("DD_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DD_SelectDate {
            get {
                return ResourceManager.GetString("DD_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the Date/time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DD_SelectDateTime {
            get {
                return ResourceManager.GetString("DD_SelectDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sum:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DD_Sum {
            get {
                return ResourceManager.GetString("DD_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   end date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DS_EndDate {
            get {
                return ResourceManager.GetString("DS_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   start date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DS_StartDate {
            get {
                return ResourceManager.GetString("DS_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DateDetails {
            get {
                return ResourceManager.GetString("Menu_DateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date Summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_DateSummary {
            get {
                return ResourceManager.GetString("Menu_DateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_NewTask {
            get {
                return ResourceManager.GetString("Menu_NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Add {
            get {
                return ResourceManager.GetString("MW_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ascending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Ascending {
            get {
                return ResourceManager.GetString("MW_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Cancel {
            get {
                return ResourceManager.GetString("MW_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   create date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_CreateDate {
            get {
                return ResourceManager.GetString("MW_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Date {
            get {
                return ResourceManager.GetString("MW_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Descending {
            get {
                return ResourceManager.GetString("MW_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Description {
            get {
                return ResourceManager.GetString("MW_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   due date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_DueDate {
            get {
                return ResourceManager.GetString("MW_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Memo {
            get {
                return ResourceManager.GetString("MW_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_More {
            get {
                return ResourceManager.GetString("MW_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open Work Holder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_OpenWorkHolder {
            get {
                return ResourceManager.GetString("MW_OpenWorkHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   priority に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Priority {
            get {
                return ResourceManager.GetString("MW_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Save {
            get {
                return ResourceManager.GetString("MW_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Search {
            get {
                return ResourceManager.GetString("MW_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Status {
            get {
                return ResourceManager.GetString("MW_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_TaskDetail {
            get {
                return ResourceManager.GetString("MW_TaskDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task Summary に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_TaskSummary {
            get {
                return ResourceManager.GetString("MW_TaskSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Tick {
            get {
                return ResourceManager.GetString("MW_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MW_Title {
            get {
                return ResourceManager.GetString("MW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ok に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NW_Ok {
            get {
                return ResourceManager.GetString("NW_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task Details に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TD_TaskDetails {
            get {
                return ResourceManager.GetString("TD_TaskDetails", resourceCulture);
            }
        }
    }
}
